# Generated by Django 5.0.6 on 2024-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_joining", models.DateField()),
                ("teacher_id", models.PositiveSmallIntegerField()),
                ("course", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=20)),
                ("bank_account_number", models.CharField(max_length=16)),
            ],
        ),
    ]
