# Generated by Django 5.0.6 on 2024-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=20)),
                ("course_id", models.PositiveSmallIntegerField()),
                ("department", models.CharField(max_length=20)),
                ("course_description", models.TextField()),
                ("class_hours", models.DurationField()),
                ("course_instructor", models.CharField(max_length=20)),
                ("assessment_requirements", models.TextField()),
                ("course_capacity", models.PositiveSmallIntegerField()),
                ("grade_level", models.CharField(max_length=15)),
                ("school_term", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
