# Generated by Django 5.0.6 on 2024-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("class_id", models.PositiveSmallIntegerField()),
                ("course", models.CharField(max_length=20)),
                ("teacher", models.CharField(max_length=20)),
                ("enrollment", models.PositiveSmallIntegerField()),
                ("room_number", models.PositiveSmallIntegerField()),
                ("class_time", models.CharField(max_length=20)),
                ("meeting_days", models.CharField(max_length=40)),
                ("academic_year", models.PositiveSmallIntegerField()),
                ("class_capacity", models.PositiveSmallIntegerField()),
                ("students", models.ManyToManyField(to="student.student")),
            ],
        ),
    ]
