# Generated by Django 5.0.6 on 2024-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
