# Generated by Django 5.0.6 on 2024-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0002_class_students'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classs',
        ),
    ]
